builds:
  -
    id: lyric
    main: ./cmd/lyric
    binary: lyric
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  -
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto
  github:
    owner: liamg
    name: lyric

