name: build

on:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17' 
    - run: go version

    - name: Run test
      run: make test

